#!/bin/bash
set -e

# Ensure critical configs exist
if [ ! -f config/database.yml ]; then
  echo "Missing config/database.yml. Copying example configs..."
  for config in amazon_s3 database vault_contents delayed_jobs domain file_store outgoing_mail security external_migration; do
    cp config/$config.yml.example config/$config.yml
  done
  cp config/dynamic_settings.yml.example config/dynamic_settings.yml
fi

if [ ! -f config/security.yml ]; then
  echo "encryption_key: \"$(openssl rand -hex 32)\"" > config/security.yml
  echo "encryption_keys:" >> config/security.yml
  echo "  - \"$(openssl rand -hex 32)\"" >> config/security.yml
fi

# Compile assets if needed
if [ ! -d public/assets ]; then
  echo "Compiling assets..."
  mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
  touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
  touch Gemfile.lock log/production.log
  bundle exec rake canvas:compile_assets
fi

# Start the app
echo "Starting Puma..."
exec bundle exec puma -C config/puma.rb
