#!/bin/bash
set -e

for file in /mnt/config/*.yml; do
  filename=$(basename "$file")
  cp "$file" config/"$filename"
done

# Compile assets if needed
#if [ ! -d public/assets ]; then
#  echo "Compiling assets..."
#  mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
#  touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
#  touch Gemfile.lock log/production.log
#  bundle exec rake canvas:compile_assets
#fi
rsync -a /mnt/public/ public/

# Start the app
echo "Starting Puma..."
exec bundle exec puma -C config/puma.rb
