#!/bin/bash
set -e

for file in /mnt/config/*.yml; do
  filename=$(basename "$file")
  cp "$file" config/"$filename"
done

# Compile assets if needed

if [ ! -d public/dist ] || [ ! -f public/dist/gulp-manifest.json ] || [ ! -f public/dist/webpack-manifest.json ]; then
  echo "Compiling assets..."
  mkdir -p log tmp/pids public/dist app/stylesheets/brandable_css_brands
  touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
  touch Gemfile.lock log/production.log
  yarn install
  bundle exec rake canvas:compile_assets
fi


# Start the app
echo "Starting Puma..."
exec bundle exec puma -C config/puma.rb
